### ISSUE TITLE
A bug  when performing asynchronous FL 

### ISSUE THREAD

**Issue by private-mechanism** [alibaba/FederatedScope#543] opened 2023-03-15 09:56 UTC
**Describe the bug**

When performing asynchronous FL, if we set client_num = 50 and sample_client_num > 47 (e.g., 48), the training procedure will remain stagnant in round #0 and never get into round #1. 

**To Reproduce**
1. Specify the FL settings as in FederatedScope/scripts/example_configs/asyn_cifar10.yaml.
2. Set "cfg.federate.client_num = 50" and "cfg.federate.sample_client_num = 48"
3. Run with command  
     ```python federatedscope/main.py --cfg scripts/example_configs/asyn_cifar10.yaml```
5. The training logs are as follows.

**Screenshots**
<img width="918" alt="image" src="https://user-images.githubusercontent.com/45845531/225267160-8b125511-e381-4c4e-a3c0-5792db773cbd.png">

**Comment by xieyxclack** [comment] 2023-03-16 11:59
Thank you for pointing out this issue. We have reproduced it and found the reason: 
- For running asyn FL with standalone mode, the received messages are pushed into the `server_msg_cache` typed as `heapq` (for ordering the received messages based on timestamps in simulation, see [here](https://github.com/alibaba/FederatedScope/blob/master/federatedscope/core/fed_runner.py#L474).
- And in the provided case, the timestamp is always 0 since no client resource file is provided for employing the cost time to generate a meaningful timestamp, and according to the `__lt__` defined in messages (see [here](https://github.com/alibaba/FederatedScope/blob/master/federatedscope/core/message.py#L93)), which would be called when sorting messages in the heap, it might happen that the messages from some of the clients are always placed at the top of the heap. And in our implementation, the message with same sender and state would be saved only once.
- Thus, the mentioned bug appears: a subset of clients (<10) repeatedly perform local training and returns feedback to the server, but the aggregation goal (=10) could not be achieved.

This issue is fixed in #546 , following:
- Add a new attribute `serial_num` to the message and modify the `__lt__` function, which ensures that when comparing the messages with same timestamp and state, the one with smaller `serial_num` would be handled first.

**Closed** 2023-03-16 12:20 UTC
