### ISSUE TITLE
" How to start with customized function?"  Some error about <Start with a customized function>

### ISSUE THREAD

**Issue by SakuraXiaMF** [alibaba/FederatedScope#367] opened 2022-09-07 02:04 UTC
When I follow "https://federatedscope.io/docs/graph/". "Start with customized function",  I get a error "ValueError: Data my_cora not found."
It seems like register_data doesn't regist my_cora data. 
My data file is mydata.py and data's feature is "mycora". My model file is mygcn.py and my model feature is "gnn_mygcb". But it doesn'r work.

How to start with customized function?

**Comment by rayrayraykk** [comment] 2022-09-07 02:49
You should place your components into `federatedscope/contrib/`, which can be found in [here](https://federatedscope.io/docs/own-case/) for details.

**Comment by SakuraXiaMF** [comment] 2022-09-07 05:40
Thank you for your reply. But, my data file "mydata.py" is located in federatedscope/contrib/data/ folder and model file "mymodel.py" is located in federatedscope/contrib/model/ folder.  But I still can't execute it, it reports an error as: "raise ValueError('Data {} not found.'.format(config.data.type))
ValueError: Data mycora not found.", it looks like my data and model are not registered successfully

**Comment by SakuraXiaMF** [comment] 2022-09-07 05:55
Oh God, I don't know why, this problem is solved

**Comment by rayrayraykk** [comment] 2022-09-07 06:04
If you have any other questions, please feel free to contact us. :)

As the problem is solved, I close this issue.

**Closed by rayrayraykk** 2022-09-07 06:04 UTC

**Comment by dikjstra** [comment] 2022-09-16 07:54
你好，请问你是怎么解决这个问题呢，我也遇到了相同的问题

**Comment by SakuraXiaMF** [comment] 2022-09-18 12:28
> 你好，请问你是怎么解决这个问题呢，我也遇到了相同的问题

您好，我是删除了原本的conda环境，之后按照开发者模式重新安装即可。
In "https://github.com/alibaba/FederatedScope"

**From source**
python setup.py install 
上面这个是安装，就是把Fedscope当成一个包用。
# Or (for dev mode)
pip install -e .[dev]
pre-commit install
这个是开发者模式，可以用来开发Fedscope。
你输入 pip install -e . 
即可以开发者模式进行部署安装
